spring.application.name=biblioteca

#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:biblioteca
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=postgres
#spring.datasource.password=root
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

server.port=8443
server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-type=PKCS12
server.ssl.key-store-password=contrasenya
server.ssl.key-alias=biblioteca-app

spring.jpa.database=POSTGRESQL
spring.sql.init.platform=postgres
spring.datasource.url=jdbc:postgresql://localhost:5433/biblioteca
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
debug=true
logging.level.org.springframework.security=DEBUG

logging.level.root=INFO
logging.level.org.apache.catalina.core=DEBUG
logging.level.org.apache.coyote.http11=DEBUG